spring:
  mvc:
    # 需要将所有页面中引用静态资源得地方都补充完整为 /static/js
    # static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://172.16.20.122:3306/test?autoReconnect=true&initialTimeout=3&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: dxyt
    password: dxyt@2020=-
    driver-class-name: com.mysql.jdbc.Driver
    #filters: stat, wall
    #max-active: 12
    druid:
      # 监控springBean -这个包下的所有东西都监控
      aop-patterns: com.atguigu.admin.*
      # 开启几个功能组件--> 监控stat--sql监控 和 wall--防火墙
      filters: stat, wall
      # 对某个功能组件进行详细配置
      filter:
        stat:
          enabled: true
          slow-sql-millis: 1000
          log-slow-sql: true
        wall:
          enabled: true
          config:
            update-allow: false
      # 配置监控页功能
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false
      # 监控web
      web-stat-filter:
        enabled: true
        url-pattern: '/*'
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
mybatis:
  #全局配置文件位置
  #config-location: classpath:mybatis/mybatis-config.xml
  #sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml
  #开启这个，需要关闭上面的全局配置文件位置，可以不写全局；配置文件，所有全局配置文件的配置都放在configuration配置项中即可
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
