server:
  port: 9009
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.20.103:3306/ucenterv2?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: dxyt
    password: dxyt@2020=-

config:
  jwt:
    expiration: 86400
task:
  sync_data: "*/5 * * * * ?"
auth:
  account: 1
  md5key: 6w4Xn52v5eLSM2Fz
  expiration: 50000

common:
  projectCode: dxyt
  createAccount: true
  idCardCheck: false
